// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJDuI0LQN-nyCEXAtpYMcwJhSHVcP9ikE',
    appId: '1:884993478901:web:c12db1d0232aad75fd35bc',
    messagingSenderId: '884993478901',
    projectId: 'qr-app-2c4f3',
    authDomain: 'qr-app-2c4f3.firebaseapp.com',
    storageBucket: 'qr-app-2c4f3.firebasestorage.app',
    measurementId: 'G-B9VXP18XB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOIPeseFr3ZAz9kJZFRdByN4uKGDXMO20',
    appId: '1:884993478901:android:0b0f00b9f0c59676fd35bc',
    messagingSenderId: '884993478901',
    projectId: 'qr-app-2c4f3',
    storageBucket: 'qr-app-2c4f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbL3YWMQFOt2LbWZO0mTH-AoOlRN-vLvI',
    appId: '1:884993478901:ios:3c3d2e1975bba515fd35bc',
    messagingSenderId: '884993478901',
    projectId: 'qr-app-2c4f3',
    storageBucket: 'qr-app-2c4f3.firebasestorage.app',
    iosBundleId: 'com.example.qrProductApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbL3YWMQFOt2LbWZO0mTH-AoOlRN-vLvI',
    appId: '1:884993478901:ios:3c3d2e1975bba515fd35bc',
    messagingSenderId: '884993478901',
    projectId: 'qr-app-2c4f3',
    storageBucket: 'qr-app-2c4f3.firebasestorage.app',
    iosBundleId: 'com.example.qrProductApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJDuI0LQN-nyCEXAtpYMcwJhSHVcP9ikE',
    appId: '1:884993478901:web:923104e7d5482f37fd35bc',
    messagingSenderId: '884993478901',
    projectId: 'qr-app-2c4f3',
    authDomain: 'qr-app-2c4f3.firebaseapp.com',
    storageBucket: 'qr-app-2c4f3.firebasestorage.app',
    measurementId: 'G-91J5Q19Z33',
  );
}
